version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    container_name: nafal-db
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: nafal
      POSTGRES_PASSWORD: nafal1234
      POSTGRES_DB: nafal
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
